# Generated by Django 4.2.10 on 2025-12-14 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('tcp_syn_scan', 'TCP SYN扫描'), ('anomaly_detect', '异常流量探测'), ('traffic_analyze', '流量数据分析'), ('ip_track', 'IP轨迹追踪')], max_length=20, verbose_name='任务类型')),
                ('target', models.CharField(max_length=500, verbose_name='目标（IP/文件路径）')),
                ('params', models.JSONField(default=dict, help_text='JSON格式，如{"ports":"1-1000","timeout":10}', verbose_name='任务参数')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result_path', models.FileField(blank=True, null=True, upload_to='task_results/%Y/%m/%d', verbose_name='结果文件路径')),
                ('result_summary', models.JSONField(default=dict, help_text='任务结果的简要信息', verbose_name='结果摘要')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '任务管理',
                'verbose_name_plural': '任务管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_level', models.CharField(choices=[('admin', '系统管理员'), ('security_admin', '安全管理员'), ('operator', '普通操作员'), ('viewer', '只读查看者')], max_length=20, unique=True, verbose_name='角色等级')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='角色描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='关联用户组')),
            ],
            options={
                'verbose_name': 'RBAC角色',
                'verbose_name_plural': 'RBAC角色',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('task_create', '创建任务'), ('task_execute', '执行任务'), ('task_delete', '删除任务'), ('signature_update', '更新特征库'), ('user_manage', '用户管理'), ('system_config', '系统配置')], max_length=30, verbose_name='权限类型')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='是否允许')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='权限描述')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboard.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': 'RBAC权限',
                'verbose_name_plural': 'RBAC权限',
                'unique_together': {('role', 'permission_type')},
            },
        ),
    ]
