# Generated by Django 4.2.10 on 2025-12-15 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': '监控任务', 'verbose_name_plural': '监控任务'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='params',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_summary',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='结果路径'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target',
            field=models.CharField(max_length=200, verbose_name='目标（IP/网段）'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('scan', '端口扫描'), ('traffic', '流量分析'), ('anomaly', '异常检测')], max_length=20, verbose_name='任务类型'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
