# Generated by Django 5.2.7 on 2025-10-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('target', models.TextField(verbose_name='扫描目标')),
                ('scan_type', models.CharField(max_length=50, verbose_name='扫描类型')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
            },
        ),
    ]
