# Generated by Django 4.2.16 on 2025-11-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcap_file_path', models.CharField(max_length=512, verbose_name='PCAP文件路径')),
                ('analyzer_type', models.CharField(choices=[('ws', 'ws-traffic-analyze-kit'), ('cic', 'CICFlowMeter')], max_length=20, verbose_name='分析器类型')),
                ('analysis_result', models.JSONField(verbose_name='分析结果')),
                ('packet_count', models.IntegerField(default=0, verbose_name='数据包数量')),
                ('protocol_distribution', models.JSONField(default=dict, verbose_name='协议分布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流量分析结果',
                'verbose_name_plural': '流量分析结果',
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('target', models.TextField(help_text='IP地址、网段或域名，多个用逗号分隔', verbose_name='扫描目标')),
                ('scan_type', models.CharField(choices=[('SYN_SCAN', 'SYN端口扫描'), ('UDP_SCAN', 'UDP端口扫描'), ('OS_DETECTION', '操作系统检测'), ('SERVICE_DETECTION', '服务版本检测'), ('FULL_SCAN', '全面扫描')], max_length=50, verbose_name='扫描类型')),
                ('ports', models.CharField(default='1-1000', help_text='例如: 80,443,1-1000', max_length=500, verbose_name='端口范围')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='扫描选项')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '进行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(verbose_name='源IP')),
                ('destination_ip', models.GenericIPAddressField(verbose_name='目标IP')),
                ('connection_type', models.CharField(max_length=50, verbose_name='连接类型')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scantask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '网络拓扑',
                'verbose_name_plural': '网络拓扑',
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='设备厂商')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口号')),
                ('protocol', models.CharField(default='tcp', max_length=10, verbose_name='协议')),
                ('state', models.CharField(max_length=20, verbose_name='状态')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='服务名称')),
                ('service_version', models.CharField(blank=True, max_length=255, verbose_name='服务版本')),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='TTL值')),
                ('rtt', models.FloatField(blank=True, null=True, verbose_name='往返时间(ms)')),
                ('os_family', models.CharField(blank=True, max_length=100, verbose_name='操作系统家族')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='操作系统版本')),
                ('fingerprint', models.JSONField(default=dict, verbose_name='设备指纹')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanner.scantask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '扫描结果',
                'verbose_name_plural': '扫描结果',
                'ordering': ['task', 'ip_address', 'port'],
                'indexes': [models.Index(fields=['ip_address'], name='scanner_sca_ip_addr_4d5d6e_idx'), models.Index(fields=['task', 'state'], name='scanner_sca_task_id_e27b24_idx')],
            },
        ),
    ]
