# Generated by Django 4.2.16 on 2025-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficanalysisresult',
            name='is_analyzed',
            field=models.BooleanField(default=False, verbose_name='是否已分析'),
        ),
    ]
