# Generated by Django 4.2.16 on 2025-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_scantask_options_scantask_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcap_file_path', models.CharField(max_length=500, verbose_name='PCAP文件路径')),
                ('analysis_result', models.JSONField(default=dict, verbose_name='分析结果')),
                ('packet_count', models.IntegerField(default=0, verbose_name='数据包数量')),
                ('protocol_distribution', models.JSONField(default=dict, verbose_name='协议分布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流量分析结果',
                'verbose_name_plural': '流量分析结果',
            },
        ),
    ]
