# Generated by Django 4.2.16 on 2025-12-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_trafficanalysisresult_is_analyzed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('src_ip', models.GenericIPAddressField(verbose_name='源IP')),
                ('dst_ip', models.GenericIPAddressField(verbose_name='目的IP')),
                ('src_port', models.IntegerField(blank=True, null=True, verbose_name='源端口')),
                ('dst_port', models.IntegerField(blank=True, null=True, verbose_name='目的端口')),
                ('protocol', models.CharField(max_length=10, verbose_name='协议')),
                ('flow_duration', models.FloatField(verbose_name='流持续时间')),
                ('total_fwd_packets', models.IntegerField(verbose_name='正向数据包数')),
                ('total_backward_packets', models.IntegerField(verbose_name='反向数据包数')),
                ('total_fwd_bytes', models.IntegerField(verbose_name='正向字节数')),
                ('total_backward_bytes', models.IntegerField(verbose_name='反向字节数')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scantask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '网络流量流',
                'verbose_name_plural': '网络流量流',
            },
        ),
        migrations.CreateModel(
            name='TrafficAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('analysis_type', models.CharField(max_length=50, verbose_name='分析类型')),
                ('result_summary', models.JSONField(verbose_name='结果摘要')),
                ('detailed_report', models.TextField(blank=True, null=True, verbose_name='详细报告')),
                ('related_flows', models.ManyToManyField(blank=True, to='scanner.trafficflow', verbose_name='相关流量流')),
            ],
            options={
                'verbose_name': '流量分析结果',
                'verbose_name_plural': '流量分析结果',
            },
        ),
    ]
