# Generated by Django 4.2.16 on 2025-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_trafficflow_trafficanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery任务ID', max_length=255, null=True),
        ),
    ]
