# Generated by Django 4.2.16 on 2025-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scantask_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='国家/地区'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='trafficanalysisresult',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间'),
        ),
        migrations.AddField(
            model_name='trafficanalysisresult',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分析开始时间'),
        ),
        migrations.AddIndex(
            model_name='networktopology',
            index=models.Index(fields=['source_ip', 'destination_ip'], name='scanner_net_source__d5cf25_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['discovered_at'], name='scanner_sca_discove_763795_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['status'], name='scanner_sca_status_38baa7_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['created_at'], name='scanner_sca_created_8c5e02_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficanalysisresult',
            index=models.Index(fields=['is_analyzed'], name='scanner_tra_is_anal_8c92a2_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficanalysisresult',
            index=models.Index(fields=['created_at'], name='scanner_tra_created_cb4726_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficflow',
            index=models.Index(fields=['timestamp'], name='scanner_tra_timesta_98f1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficflow',
            index=models.Index(fields=['src_ip', 'dst_ip'], name='scanner_tra_src_ip_005f1c_idx'),
        ),
    ]
